name: Deploy Nuxt

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Nuxt.js to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_FRONT_HOST_NAME }}
          username: ${{ secrets.EC2_FRONT_USER_NAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          timeout: 180s
          script: |
            cd /nilgiri
            git fetch --prune
            git checkout master
            git pull origin master
            yarn generate
            sudo systemctl restart nuxt
